# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180216_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_zip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_zip',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone2',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_state',
            field=models.CharField(max_length=50),
        ),
    ]
