# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180222_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='shippingAddress_1',
            new_name='shippingAddress1',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='shippingAddress_2',
            new_name='shippingAddress2',
        ),
    ]
