# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180222_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone2',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
