# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetailsc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastName',
        ),
    ]
