# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetailsc', '0002_auto_20180227_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Unqiue value for product page URL, created from name.'),
        ),
    ]
