# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetailsc', '0003_auto_20180509_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='metaDescription',
            field=models.CharField(blank=True, help_text='Content for desciption meta tag', max_length=255, null=True, verbose_name='Meta Description '),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unqiue value for product page URL, created from name.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnailImage',
            field=models.FileField(blank=True, null=True, upload_to='static/bookdetailsc/soimages/category/thumbnails'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
